"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowUp, Bot, Database, LoaderCircle } from "lucide-react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:8000";
type Answer={intent:string;answer:string;source_work_ids:string[];matched_entity_ids:string[];links:{label:string;href:string}[]};
const examples=["《嫌疑人X的献身》中石神和靖子是什么关系？","《罗杰疑案》的关键时间线是什么？","三部作品分别用了什么诡计？","《东方快车谋杀案》的杀人手法是什么？"];

export default function ChatPage(){const[question,setQuestion]=useState("");const[answer,setAnswer]=useState<Answer|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function submit(event?:FormEvent){event?.preventDefault();if(!question.trim())return;setLoading(true);setError("");setAnswer(null);try{const response=await fetch(`${API}/chat/query`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});if(!response.ok)throw new Error("检索失败");setAnswer(await response.json())}catch{setError("暂时无法连接知识库，请确认本地 API 已启动。")}finally{setLoading(false)}}return <main className="chatPage"><section className="pageIntro"><p className="eyebrow">ASK THE DOSSIER</p><h1>对话检索</h1><p>回答只使用已收录的三部作品数据；数据不足时会明确说明。</p></section><div className="chatWindow"><div className="assistantHello"><Bot/><div><b>你可以问我人物关系、时间线、诡计或杀人手法。</b><p>试试下面的问题，或直接输入你自己的问题。</p></div></div><div className="exampleRow">{examples.map(item=><button key={item} onClick={()=>setQuestion(item)}>{item}</button>)}</div>{answer&&<section className="answerBlock"><div className="answerLabel"><Bot size={18}/> WorkDossier 回答</div>{answer.answer.split("\n").map((line,index)=><p key={index}>{line}</p>)}<div className="answerLinks">{answer.links.map(link=><Link key={link.href+link.label} href={link.href}>{link.label} →</Link>)}</div><details><summary><Database size={14}/> 查看检索依据</summary><small>作品范围：{answer.source_work_ids.join(" · ")}</small><small>命中实体：{answer.matched_entity_ids.join(" · ")||"无"}</small></details></section>}{error&&<p className="errorText">{error}</p>}<form onSubmit={submit} className="chatInput"><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="输入关于三部作品的问题…"/><button aria-label="发送问题" disabled={loading||!question.trim()}>{loading?<LoaderCircle className="spin"/>:<ArrowUp/>}</button></form></div></main>}