"use client";
import {useEffect,useState} from "react";import {CheckCircle2,LoaderCircle,Microscope,Search,ShieldCheck} from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:8000";
type Work={work_id:string;canonical_title:string;media_type:string;release_year?:number;creators:string[]};type Item={section:string;question:string;priority:number;queries:string[];preferred_sources:string[];minimum_sources:number;enabled:boolean};type Job={job_id:string;work:Work;base_version:string;target_version:string;status:string;plan?:{items:Item[];estimated_queries:number;estimated_sources:number;estimated_model_tokens:number;approved:boolean};coverage:any[];sources:any[];snapshots:any[];evidence:any[];claims:any[];proposals:any[];report?:any;knowledge_package?:any;diff:Record<string,number>;errors:string[];usage:Record<string,number>};
export default function ResearchPage(){const[works,setWorks]=useState<any[]>([]),[mode,setMode]=useState("new"),[selected,setSelected]=useState(""),[title,setTitle]=useState(""),[media,setMedia]=useState("novel"),[candidates,setCandidates]=useState<Work[]>([]),[resolution,setResolution]=useState(""),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
useEffect(()=>{fetch(API+"/dossiers").then(r=>r.json()).then(d=>{setWorks(d);if(d[0])setSelected(d[0].work.work_id)})},[]);useEffect(()=>{if(!job||!["searching","reading","extracting","verifying","proposing","reflecting","drafting","retrying"].includes(job.status))return;const t=setInterval(()=>fetch(`${API}/research/jobs/${job.job_id}`).then(r=>r.json()).then(setJob),800);return()=>clearInterval(t)},[job]);
async function create(work?:Work){setBusy(true);setError("");try{let body:any;if(mode==="existing")body={work_id:selected};else if(work)body={work};else{const rr=await fetch(API+"/works/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:title,media_type:media})});const resolved=await rr.json();setResolution(resolved.resolution_id);if(resolved.needs_confirmation){setCandidates(resolved.candidates);return}body={work:resolved.resolved_work}}const r=await fetch(API+"/research/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail);setJob(d)}catch(e:any){setError(e.message||"创建失败")}finally{setBusy(false)}}
async function confirm(w:Work){await fetch(`${API}/works/resolve/${resolution}/confirm`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({work_id:w.work_id})});setCandidates([]);await create(w)}
function toggle(i:number){if(!job?.plan)return;const items=job.plan.items.map((x,n)=>n===i?{...x,enabled:!x.enabled}:x);setJob({...job,plan:{...job.plan,items}})}
async function approvePlan(){if(!job?.plan)return;setBusy(true);const r=await fetch(`${API}/research/jobs/${job.job_id}/plan/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:job.plan.items})});setJob(await r.json());setBusy(false)}
async function review(){if(!job)return;const r=await fetch(`${API}/research/jobs/${job.job_id}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approved_proposal_ids:job.proposals.map(p=>p.proposal_id),rejected_proposal_ids:[]})});setJob(await r.json())}
async function publish(){if(!job)return;const r=await fetch(`${API}/research/jobs/${job.job_id}/publish`,{method:"POST"});const d=await r.json();if(r.ok)setJob(d);else setError(d.detail)}
return <main className="researchPage"><section className="pageIntro"><p className="eyebrow">WORKDOSSIER RESEARCH 0.3</p><h1>作品深度研究</h1><p>先确认作品，再审核研究计划；所有知识变更都可追溯到正文证据。</p></section><section className="researchWorkspace">
{!job&&<section className="researchSetupV3"><div className="modeTabs"><button className={mode==="new"?"active":""} onClick={()=>setMode("new")}>新作品</button><button className={mode==="existing"?"active":""} onClick={()=>setMode("existing")}>已有作品</button></div>{mode==="new"?<div className="intakeFields"><label>作品名<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：无人生还"/></label><label>类型<select value={media} onChange={e=>setMedia(e.target.value)}><option value="novel">小说</option><option value="film">电影</option><option value="series">剧集</option><option value="game">游戏</option><option value="manga">漫画</option></select></label></div>:<label>选择知识库作品<select value={selected} onChange={e=>setSelected(e.target.value)}>{works.map(w=><option value={w.work.work_id} key={w.work.work_id}>{w.work.canonical_title} · {w.dossier_version}</option>)}</select></label>}<button className="primaryAction" disabled={busy||(mode==="new"?!title:!selected)} onClick={()=>create()}>{busy?<LoaderCircle className="spin"/>:<Microscope/>}生成研究计划</button></section>}
{candidates.length>0&&<section className="candidatePanel"><h2>请选择具体作品</h2><p>发现多个可信候选，只需在这里确认作者、年份或版本。</p>{candidates.map(c=><button key={c.work_id} onClick={()=>confirm(c)}><b>{c.canonical_title}</b><span>{c.creators.join(" · ")||"作者未知"} · {c.release_year||"年份未知"} · {c.media_type}</span></button>)}</section>}
{job&&<><div className="jobHeader"><div><small>{job.job_id}</small><h2>《{job.work.canonical_title}》</h2><p>{job.base_version} → {job.target_version}</p></div><span className="status">{job.status}</span></div>{job.status==="awaiting_plan_approval"&&job.plan&&<section className="researchSection"><h2>审核 Research Plan</h2><div className="budgetLine"><span>查询 ≤ {job.plan.estimated_queries}</span><span>来源 ≤ {job.plan.estimated_sources}</span><span>Token ≤ {job.plan.estimated_model_tokens}</span></div><div className="planList">{job.plan.items.map((x,i)=><article key={x.section} className={x.enabled?"enabled":"disabled"}><input type="checkbox" checked={x.enabled} onChange={()=>toggle(i)}/><div><b>{x.section}</b><p>{x.question}</p><small>{x.queries.join(" · ")}</small></div><select value={x.priority} onChange={e=>{const items=[...job.plan!.items];items[i]={...x,priority:Number(e.target.value)};setJob({...job,plan:{...job.plan!,items}})}}>{[5,4,3,2,1].map(n=><option key={n}>{n}</option>)}</select></article>)}</div><button className="primaryAction" onClick={approvePlan} disabled={busy}>批准并启动</button></section>}
{job.status!=="awaiting_plan_approval"&&<><div className="metricGrid"><article><Search/><strong>{job.usage.queries||0}</strong><span>查询</span></article><article><ShieldCheck/><strong>{job.evidence.length}</strong><span>可定位证据</span></article><article><CheckCircle2/><strong>{job.proposals.length}</strong><span>知识变更</span></article></div>{job.errors.map(e=><p className="errorText" key={e}>{e}</p>)}{job.report&&<section className="researchSection"><h2>{job.report.title}</h2><p>{job.report.summary}</p><div className="proposalList">{job.report.sections.map((section:any)=><article key={section.section_id}><div><b>{section.title}</b><p>{section.body}</p></div></article>)}</div></section>}{job.knowledge_package&&<section className="researchSection"><h2>知识包摘要</h2><div className="budgetLine"><span>人物 {job.knowledge_package.characters.length}</span><span>关系 {job.knowledge_package.relationships.length}</span><span>时间线 {job.knowledge_package.timeline.length}</span><span>诡计 {job.knowledge_package.tricks.length}</span><span>杀人方法 {job.knowledge_package.murder_methods.length}</span></div></section>}{job.sources?.length>0&&<section className="researchSection"><h2>已读取来源</h2><div className="proposalList">{job.sources.map((source:any)=><article key={source.source_id}><span>{Math.round(source.credibility*100)}%</span><div><b>{source.title}</b><p>{source.source_type} · {source.url}</p></div></article>)}</div></section>}{job.proposals.length>0&&<section className="researchSection"><h2>证据级审核</h2><div className="evidenceTable"><b>知识变更</b><b>支持 Claim</b><b>原始证据与定位</b>{job.proposals.map(p=>{const c=job.claims.find(x=>x.claim_id===p.claim_ids[0]),e=job.evidence.find(x=>x.evidence_id===p.evidence_ids[0]),s=job.snapshots.find(x=>x.snapshot_id===e?.snapshot_id);return <div className="evidenceRow" key={p.proposal_id}><span>{p.target_section}: {p.summary}</span><span>{c?.text}</span><span>“{e?.quote}”<small>{s?.url} · 段落 {e?.locator?.paragraph}</small></span></div>})}</div>{job.status==="needs_review"&&<div className="publishBar"><button onClick={review}>批准全部变更</button><button className="primary" onClick={publish}>发布 {job.target_version}</button></div>}</section>}</>}{job.status==="published"&&<div className="publishedNotice"><CheckCircle2/><div><b>WorkDossier {job.target_version} 已发布</b><p>新增 {job.diff.added_entities||0} 个实体、{job.diff.added_claims||0} 条 Claim。</p></div></div>}</>}{error&&<p className="errorText">{error}</p>}</section></main>}
